### ISSUE TITLE
Create bio page

### ISSUE THREAD

**Issue by FarhanB2** [csci-2479-sp-2022/individual-lab-1#26]
Create an html file with the name firstname-lastname.html under your team directory
This file should contain a brief bio about yourself. Feel free to include information similar to what was shared in the icebreaker, such as:
Where you are from originally
Your major/track at CSCC
What you hope to do after school
What you enjoy doing as a hobby or pastime

**Comment by Shahemc** [comment]
Everyone has dont this so im going to close it.
