### ISSUE TITLE
Create Team Name for Team One

### ISSUE THREAD

**Issue by jimmymccue** [csci-2479-sp-2022/individual-lab-1#3]
I'm thinking Andrew got it right in the first place. Team One! Lol

**Comment by jimmymccue** [comment]
We have decided on our team name. Just to toy around with this process of issues and such I have assigned it to Carrie.

**Comment by ckohner** [comment]
![20190627_111726](https://user-images.githubusercontent.com/80296811/151870382-19f62e11-155b-4b80-99fd-afd6038a61f9.jpg)

We agreed on Fly High 9 or ^9^ in shorthand
